//! Generates `SM83/Decode.lean` — a Lean mirror of the ALU-block decoder.
//!
//! The decode table is computed by *actually running* the Rust decoder
//! on every opcode in the binary-ALU block `0x80..=0xBF`. No bit-slicing,
//! variant ordering, or opcode layout logic is duplicated in Lean: if the
//! Rust decoder ever changes, the next extractor run picks up the new
//! behaviour automatically.
//!
//! Scope: the 64 opcodes of `0x80..=0xBF` only. This is the minimum
//! viable decoder for the one-step refinement experiment. Other opcode
//! blocks (loads, jumps, stack ops, CB-prefix, …) will be added later.

use cpu::alu::AluOp;
use cpu::instruction::{decode::decode, GbInstruction, U8Arith};
use cpu::registers::Reg8;
use memory::TestBus;

use crate::modules::{AsModule, Module};

pub struct Sm83Decode;

impl Sm83Decode {
    pub fn extract() -> Self {
        Self
    }
}

/// All `AluOp` variants, in canonical order. The exhaustive match in
/// `alu_op_name` fails to compile if a new variant is added in
/// `cpu::alu::AluOp`, forcing a coordinated update here.
const ALU_OP_VARIANTS: &[AluOp] = &[
    AluOp::Add,
    AluOp::Adc,
    AluOp::Sub,
    AluOp::Sbc,
    AluOp::And,
    AluOp::Xor,
    AluOp::Or,
    AluOp::Cp,
];

fn alu_op_name(op: AluOp) -> &'static str {
    match op {
        AluOp::Add => "Add",
        AluOp::Adc => "Adc",
        AluOp::Sub => "Sub",
        AluOp::Sbc => "Sbc",
        AluOp::And => "And",
        AluOp::Xor => "Xor",
        AluOp::Or => "Or",
        AluOp::Cp => "Cp",
    }
}

fn reg8_name(r: Reg8) -> &'static str {
    match r {
        Reg8::A => "A",
        Reg8::B => "B",
        Reg8::C => "C",
        Reg8::D => "D",
        Reg8::E => "E",
        Reg8::F => "F",
        Reg8::H => "H",
        Reg8::L => "L",
    }
}

/// Invoke the real Rust decoder on a single opcode byte and classify the
/// result. Only `U8Arith::BinR8` and `U8Arith::BinHL` are expected in the
/// `0x80..=0xBF` window.
fn decode_alu_byte(opcode: u8) -> Option<(AluOp, Option<Reg8>)> {
    let mut bus = TestBus::new();
    bus.load_rom(0, &[opcode]);
    let (instr, _new_pc) = decode(0, &mut bus, false);
    match instr {
        GbInstruction::U8Arithmetic(U8Arith::BinR8(op, r)) => Some((op, Some(r))),
        GbInstruction::U8Arithmetic(U8Arith::BinHL(op)) => Some((op, None)),
        _ => None,
    }
}

impl AsModule for Sm83Decode {
    fn as_module(&self) -> std::io::Result<Module> {
        let mut out = String::new();
        out.push_str("-- Auto-generated ALU-block decoder mirror.\n");
        out.push_str("-- Source of truth: lib/crates/cpu/src/instruction/decode.rs\n");
        out.push_str("-- Every table entry is produced by invoking the real Rust decoder\n");
        out.push_str("-- at extractor-build time — no bit-slicing or opcode layout logic\n");
        out.push_str("-- is duplicated in Lean. Do not edit by hand.\n\n");

        // ----- AluOp -----
        out.push_str("/-- Binary ALU operations (mirrors `cpu::alu::AluOp`). -/\n");
        out.push_str("inductive AluOp : Type\n");
        for op in ALU_OP_VARIANTS {
            out.push_str(&format!("  | {}\n", alu_op_name(*op)));
        }
        out.push_str("  deriving DecidableEq, Repr\n\n");

        // ----- decode_alu_block -----
        out.push_str(
            "/-- Decode an opcode byte in the binary-ALU block `0x80..=0xBF`.\n    Returns `some (op, src)` where `src = none` means the `(HL)` variant.\n    Every entry is generated by running the real Rust decoder at\n    extractor-build time, so there is no opcode layout logic duplicated\n    in Lean. -/\n",
        );
        out.push_str("def decode_alu_block : BitVec 8 → Option (AluOp × Option Reg8)\n");
        for opcode in 0x80u8..=0xBFu8 {
            match decode_alu_byte(opcode) {
                Some((op, Some(r))) => out.push_str(&format!(
                    "  | 0x{:02X}#8 => some (AluOp.{}, some Reg8.{})\n",
                    opcode,
                    alu_op_name(op),
                    reg8_name(r)
                )),
                Some((op, None)) => out.push_str(&format!(
                    "  | 0x{:02X}#8 => some (AluOp.{}, none)\n",
                    opcode,
                    alu_op_name(op)
                )),
                None => {
                    // Should be unreachable for 0x80..=0xBF.
                    panic!(
                        "Rust decoder returned non-ALU instruction for opcode 0x{opcode:02X}"
                    );
                }
            }
        }
        out.push_str("  | _ => none\n\n");

        // ----- Applying an AluOp to concrete inputs (dispatches to the Spec functions) -----
        out.push_str(
            "/-- Apply a decoded `AluOp` to a pair of operands, returning the\n    BitVec 8 result. This is the Lean counterpart of\n    `cpu::alu::alu_binary` minus the carry-in / flag reporting; it\n    dispatches directly to the `spec_*` functions emitted by\n    `SM83.Spec`.\n\n    Only the five *pure* ALU ops (ADD, SUB, AND, XOR, OR) have a\n    corresponding `spec_*` function today; ADC / SBC / CP take a\n    carry-in and have no spec, so we use `spec_add` / `spec_sub` as\n    placeholders there. Refinement theorems only apply to the five\n    supported cases. -/\n",
        );
        out.push_str("def AluOp.apply : AluOp → BitVec 8 → BitVec 8 → BitVec 8\n");
        for op in ALU_OP_VARIANTS {
            let spec = match op {
                AluOp::Add | AluOp::Adc => "spec_add",
                AluOp::Sub | AluOp::Sbc | AluOp::Cp => "spec_sub",
                AluOp::And => "spec_and",
                AluOp::Xor => "spec_xor",
                AluOp::Or => "spec_or",
            };
            out.push_str(&format!("  | .{}, a, b => {spec} a b\n", alu_op_name(*op)));
        }
        out.push('\n');

        Ok(Module {
            name: "Decode".into(),
            imports: vec!["SM83.RegFile".into(), "SM83.Spec".into()],
            contents: out.into_bytes(),
        })
    }
}
